### ISSUE TITLE
FYI: module build fail on node v8.x 

### ISSUE THREAD

**Issue by nxhack** [nxhack/openwrt-node-packages#113]
"make V=w" catch
```
module.js:473
      throw err;
      ^

TypeError: assertEncoding is not a function
    at getOptions (fs.js:81:5)
    at Object.realpathSync (fs.js:1584:15)
    at toRealPath (module.js:154:13)
    at Function.Module._findPath (module.js:203:22)
    at Function.Module._resolveFilename (module.js:525:25)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

"make V=s" work well

stderr redirection breaks require : https://github.com/nodejs/node/issues/11257

**Comment by nxhack** [comment]
This issue seems to occur only in the LEDE-head, LEDE 17.01 is fine.

**Comment by nxhack** [comment]
This problem was solved. close
