### ISSUE TITLE
Serialport issues

### ISSUE THREAD

**Issue by Petapton** [nxhack/openwrt-node-packages#482]
Hello. I'm getting this error when trying to use serialport (also when starting node-red).
```
> require("serialport")
Thrown:
Error: Error relocating /node_modules/@serialport/bindings/build/Release/bindings.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (/mnt/node_modules/bindings/bindings.js:112:48)

```

**Comment by Petapton** [comment]
Hello, it came out it was only a compilation error. Solved recompiling node-serialport.
